AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda stack detects changes in source s3 bucket and performs cfn update
Resources:
  LambdaServiceRole: #lambda service role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                 - lambda.amazonaws.com
            Action:
                 - sts:AssumeRole
      Path: "/"
  LambdaPolicy: #create lambda policy
    Type: AWS::IAM::Policy
    DependsOn: LambdaServiceRole
    Properties:
      PolicyName: LambdaPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:*
              - codedeploy:*
              - ec2:*
              - cloudwatch:*
              - elasticloadbalancing:*
              - s3:*
            Resource: "*"
      Roles:
        - !Ref LambdaServiceRole


 
